name: Blob storage website CI

on:
    workflow_dispatch:
    push:
        branches: [ main ]

permissions:
    id-token: write
    contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout stuff
      uses: actions/checkout@v4

    - name: Setup code
      run: |
          mkdir site
          cp -R assets site/assets
          cp *.html site/

    - name: Login
      uses: azure/login@v2
      with:
#          creds: ${{ secrets.AZURE_CREDENTIAL_SP }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/cli@v2
      with:
          inlineScript: |
              az storage blob upload-batch --account-name "gptursa" --auth-mode key --destination '$web' --source site/

    - name: Context
      run: |
          rm -R site

    - name: Purge CDN endpoint
      uses: azure/cli@v2
      with:
          inlineScript: |
              az afd endpoint purge --resource-group "gpturrg" --profile-name "gpturfdp" --endpoint-name "gpturep" --content-paths "/*"

  # Azure logout
    - name: Logout
      run: |
          az logout
      if: always()
