name: Blob storage website CI

on:
    workflow_dispatch:
    push:
        branches: [ main ]

permissions:
    id-token: write
    contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout stuff
      uses: actions/checkout@v4

    - name: Login
      uses: azure/login@v2
      with:
#          creds: ${{ secrets.AZURE_CREDENTIAL_SP }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/cli@v2
      with:
          inlineScript: |
              # az storage blob upload-batch --account-name gptur4sa --auth-mode key -d '$web' -s .
              az storage blob upload-batch --account-name "gptursa" --auth-mode key --destination '$web' --source . --pattern "assets/*"
              az storage blob upload-batch --account-name "gptursa" --auth-mode key --destination '$web' --source . --pattern "[!/].html"
              # az storage blob upload-batch --account-name "gptursa" --auth-mode key --destination '$web' --source . --pattern "assets/*" --pattern "404.html" --pattern "contacts.html" --pattern "index.html" --pattern "page3.html"

    - name: Context
      run: |
          az account show
          az group list
          pwd
          ls -alR

    - name: Purge CDN endpoint
      uses: azure/cli@v2
      with:
          inlineScript: |
              # az cdn endpoint purge --content-paths  "/*" --profile-name "gptur4p" --name "gptur" --resource-group "gptur4rg"
              az afd endpoint purge --resource-group "gpturrg" --profile-name "gpturfdp" --endpoint-name "gpturep" --content-paths "/*"

  # Azure logout
    - name: Logout
      run: |
          az logout
      if: always()
