name: Blob storage website CI

on: 
    workflow_dispatch:
    push:
        branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIAL_SP }}

    - name: Upload to blob storage
      uses: azure/cli@v2
      with:
        inlineScript: |
            # az storage blob upload-batch --account-name gptur4sa --auth-mode key -d '$web' -s .
            az storage blob upload-batch --account-name "gptursa" --auth-mode key --destination '$web' --source . --pattern "assets/*" --pattern "404.html" --pattern "contacts.html" --pattern "index.html" --pattern "page3.html"

    - name: Purge CDN endpoint
      uses: azure/cli@v2
      with:
        inlineScript: |
           # az cdn endpoint purge --content-paths  "/*" --profile-name "gptur4p" --name "gptur" --resource-group "gptur4rg"
           az afd endpoint purge --resource-group "gpturrg" --profile-name "gpturfdp" --endpoint-name "gpturep" --content-paths "/*" --no-wait

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
